/* Allegro datafile object indexes, produced by dat v4.1.13 (WIP), MSVC */
/* Datafile: fonts.dat */
/* Date: Tue Jul 20 01:46:44 2004 */
/* Do not hand edit! */

#define F20THCENTURY                     0        /* FONT */
#define ADOLESCENCE                      1        /* FONT */
#define AIRCUT                           2        /* FONT */
#define AMAZE                            3        /* FONT */
#define ANDALEMONO                       4        /* FONT */
#define ANOTHER                          5        /* FONT */
#define ANTIGONI                         6        /* FONT */
#define ARIAL                            7        /* FONT */
#define AUCOINBOLD                       8        /* FONT */
#define BAJNOMAN                         9        /* FONT */
#define BEDINI                           10       /* FONT */
#define BERMUDA                          11       /* FONT */
#define BROADWAY                         12       /* FONT */
#define CALIGRAPH                        13       /* FONT */
#define CATANEO                          14       /* FONT */
#define CENTURYGOTHIC                    15       /* FONT */
#define CMMI                             16       /* FONT */
#define COMIC                            17       /* FONT */
#define CORSIVA                          18       /* FONT */
#define CREEPY                           19       /* FONT */
#define CURLZ                            20       /* FONT */
#define DOOM                             21       /* FONT */
#define ERASERDUST                       22       /* FONT */
#define EUROSTAR                         23       /* FONT */
#define FALSTAFF                         24       /* FONT */
#define FIGARO                           25       /* FONT */
#define FIXEDSYS                         26       /* FONT */
#define FOOTLIGHT                        27       /* FONT */
#define GEORGIA                          28       /* FONT */
#define GOURMAND                         29       /* FONT */
#define HIGHLIGHT                        30       /* FONT */
#define HYENA                            31       /* FONT */
#define IMPACT                           32       /* FONT */
#define INTHACITY                        33       /* FONT */
#define IRONMAIDEN                       34       /* FONT */
#define JOHNHANDY                        35       /* FONT */
#define JOKERMAN                         36       /* FONT */
#define KIDTYPE                          37       /* FONT */
#define KUNSTLER                         38       /* FONT */
#define LABAMBA                          39       /* FONT */
#define LCD                              40       /* FONT */
#define LUICIDIA                         41       /* FONT */
#define MEKANIK                          42       /* FONT */
#define METALLORD                        43       /* FONT */
#define METRO                            44       /* FONT */
#define MGI                              45       /* FONT */
#define MISTER                           46       /* FONT */
#define MISTRAL                          47       /* FONT */
#define MODERN                           48       /* FONT */
#define ODESSA                           49       /* FONT */
#define OLDDREAD                         50       /* FONT */
#define ONESTROKE                        51       /* FONT */
#define ORANGE                           52       /* FONT */
#define ORBUS                            53       /* FONT */
#define PALACE                           54       /* FONT */
#define PALLADIUS                        55       /* FONT */
#define PARKAVENUE                       56       /* FONT */
#define PEINAUD                          57       /* FONT */
#define PLEIADES                         58       /* FONT */
#define PLUMP                            59       /* FONT */
#define PUMP                             60       /* FONT */
#define QUIXLEY                          61       /* FONT */
#define RAGE                             62       /* FONT */
#define RAUCH                            63       /* FONT */
#define SCRUFF                           64       /* FONT */
#define SIMPSON                          65       /* FONT */
#define SKETCHY                          66       /* FONT */
#define SMUDGER                          67       /* FONT */
#define SPACETOASTER                     68       /* FONT */
#define SQUARE                           69       /* FONT */
#define STACCATO                         70       /* FONT */
#define TAHOMA                           71       /* FONT */
#define TEAMMT                           72       /* FONT */
#define TIRANTI                          73       /* FONT */
#define VIANTA                           74       /* FONT */
#define VICTORAIN                        75       /* FONT */
#define WENDY                            76       /* FONT */
#define WESTMINDER                       77       /* FONT */
#define WESTWOOD                         78       /* FONT */
#define WOFACHABCER                      79       /* FONT */
#define WOFALDE                          80       /* FONT */
#define WOFAMBROS                        81       /* FONT */
#define WOFAMERUNI                       82       /* FONT */
#define WOFANDRO                         83       /* FONT */
#define WOFARGENT                        84       /* FONT */
#define WOFARIZONA                       85       /* FONT */
#define WOFARROW                         86       /* FONT */
#define WOFARTE                          87       /* FONT */
#define WOFBAIDER                        88       /* FONT */
#define WOFBARIUM                        89       /* FONT */
#define WOFBASTIA                        90       /* FONT */
#define WOFBATS                          91       /* FONT */
#define WOFBILIA                         92       /* FONT */
#define WOFBLADE                         93       /* FONT */
#define WOFBLIXA                         94       /* FONT */
#define WOFBONIX                         95       /* FONT */
#define WOFBORDER                        96       /* FONT */
#define WOFBOROLD                        97       /* FONT */
#define WOFBORSCH                        98       /* FONT */
#define WOFBURO                          99       /* FONT */
#define WOFCANDI                         100      /* FONT */
#define WOFCHIRO                         101      /* FONT */
#define WOFCLIPS                         102      /* FONT */
#define WOFCLOCK                         103      /* FONT */
#define WOFCLOCKER                       104      /* FONT */
#define WOFCOOL                          105      /* FONT */
#define WOFDELLI                         106      /* FONT */
#define WOFDRAKER                        107      /* FONT */
#define WOFEDUK                          108      /* FONT */
#define WOFELECTRO                       109      /* FONT */
#define WOFFIRNIS                        110      /* FONT */
#define WOFFITIO                         111      /* FONT */
#define WOFFLOW                          112      /* FONT */
#define WOFFUTUR                         113      /* FONT */
#define WOFGINEWRA                       114      /* FONT */
#define WOFHANDS                         115      /* FONT */
#define WOFHARDSH                        116      /* FONT */
#define WOFINTONA                        117      /* FONT */
#define WOFJOKER                         118      /* FONT */
#define WOFNEWART                        119      /* FONT */
#define WST                              120      /* FONT */

